<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>io.github.dfa1</groupId>
		<artifactId>rocksdbffm</artifactId>
		<version>0.6.1-SNAPSHOT</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>

	<artifactId>rocksdbffm-native-linux-aarch64</artifactId>
	<name>RocksDB FFM Native Linux aarch64</name>
	<packaging>jar</packaging>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>build-rocksdb-native</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>${maven.multiModuleProjectDirectory}/scripts/build-rocksdb.sh</executable>
							<arguments>
								<argument>${project.basedir}/src/main/resources</argument>
								<argument>linux-aarch64</argument>
							</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
